//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class product
    {
        [Key]
        public int product_id { get; set; }

        [Required] //поле не может быть пустым, если пустое, значит показывается сообщегние
        [Display(Name = "Название товара")] //то, что будет показано
        public string product_name { get; set; }
        [Required]
        [Display(Name = "Категория")]
        public string category { get; set; }
        [Required]
        [Display(Name = "Описание товара")]
        public string description { get; set; }
        [Required]
        [Display(Name = "Производитель товара")]
        public string manufacturer { get; set; }
        [Range(1, int.MaxValue)] //цена товаара не может быть отрицательным, то есть от 1 до максимального числа Int
        [Display(Name = "Цена")]
        public Nullable<int> price { get; set; }
        public Nullable<int> productOrder_id { get; set; }

        public virtual order order { get; set; } 

       

    }
}
